### ISSUE TITLE
Failed to upgrade pluygin to version 2.1.0

### ISSUE THREAD

**Issue by delanick** [EddyVerbruggen/nativescript-pushy#17]
Hey @EddyVerbruggen getting the following error when attempting to upgrade:

`App with path: /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt was opened.
[19-09-08 20:54:53.963] {"stack":"Error: Command npm failed with exit code 243 Error output: \n npm WARN checkPermissions Missing write access to /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy\nnpm WARN checkPermissions Missing write access to /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules\nnpm WARN ts-loader@5.4.5 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.\n\nnpm ERR! path /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy\nnpm ERR! code EACCES\nnpm ERR! errno -13\nnpm ERR! syscall access\nnpm ERR! Error: EACCES: permission denied, access '/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy'\nnpm ERR!  { [Error: EACCES: permission denied, access '/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy']\nnpm ERR!   stack:\nnpm ERR!    'Error: EACCES: permission denied, access \\'/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy\\'',\nnpm ERR!   errno: -13,\nnpm ERR!   code: 'EACCES',\nnpm ERR!   syscall: 'access',\nnpm ERR!   path:\nnpm ERR!    '/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy' }\nnpm ERR! \nnpm ERR! The operation was rejected by your operating system.\nnpm ERR! It is likely you do not have the permissions to access this file as the current user\nnpm ERR! \nnpm ERR! If you believe this might be a permissions issue, please double-check the\nnpm ERR! permissions of the file and its containing directories, or try running\nnpm ERR! the command again as root/Administrator (though this is not recommended).\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/nickdelahunt/.npm/_logs/2019-09-08T18_54_53_929Z-debug.log\n\n    at ChildProcess.childProcess.on (/usr/local/lib/node_modules/nativescript/lib/common/child-process.js:129:36)\n    at ChildProcess.emit (events.js:198:13)\n    at maybeClose (internal/child_process.js:982:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)","message":"Command npm failed with exit code 243 Error output: \n npm WARN checkPermissions Missing write access to /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy\nnpm WARN checkPermissions Missing write access to /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules\nnpm WARN ts-loader@5.4.5 requires a peer of typescript@* but none is installed. You must install peer dependencies yourself.\n\nnpm ERR! path /Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy\nnpm ERR! code EACCES\nnpm ERR! errno -13\nnpm ERR! syscall access\nnpm ERR! Error: EACCES: permission denied, access '/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy'\nnpm ERR!  { [Error: EACCES: permission denied, access '/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy']\nnpm ERR!   stack:\nnpm ERR!    'Error: EACCES: permission denied, access \\'/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy\\'',\nnpm ERR!   errno: -13,\nnpm ERR!   code: 'EACCES',\nnpm ERR!   syscall: 'access',\nnpm ERR!   path:\nnpm ERR!    '/Users/nickdelahunt/Documents/OneDrive/wigital/Programmes/WeSignIt/Product/Mobile App/Project files/Prod/WeSignIt/node_modules/nativescript-pushy' }\nnpm ERR! \nnpm ERR! The operation was rejected by your operating system.\nnpm ERR! It is likely you do not have the permissions to access this file as the current user\nnpm ERR! \nnpm ERR! If you believe this might be a permissions issue, please double-check the\nnpm ERR! permissions of the file and its containing directories, or try running\nnpm ERR! the command again as root/Administrator (though this is not recommended).\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /Users/nickdelahunt/.npm/_logs/2019-09-08T18_54_53_929Z-debug.log\n"}`

I'm using Sidekick - could it be a Sidekick issue?

**Comment by delanick** [comment]
@EddyVerbruggen Installed it via CLI and it worked fine. Sidekick must not have access :)
